CREATE TABLE [dbo].[tbl_IFace_WellTestAutomationToIngres] (
    [TransID]          INT              IDENTITY (1, 1) NOT NULL,
    [TransSeq]         INT              NOT NULL,
    [IFaceBatchUID]    UNIQUEIDENTIFIER NOT NULL,
    [TranStatus]       INT              NULL,
    [TranDate]         DATETIME         NULL,
    [TranMsg]          NVARCHAR (MAX)   NULL,
    [PubID]            INT              NOT NULL,
    [Tes_Date]         DATETIME         NULL,
    [WELL_NAME]        VARCHAR (50)     NULL,
    [LEASE]            VARCHAR (50)     NULL,
    [BGPD]             VARCHAR (50)     NULL,
    [BOPD]             VARCHAR (50)     NULL,
    [CSG_PRESS]        VARCHAR (50)     NULL,
    [TBG_PRESS]        VARCHAR (50)     NULL,
    [MCFD]             VARCHAR (50)     NULL,
    [GOR]              VARCHAR (50)     NULL,
    [FLTBG]            VARCHAR (50)     NULL,
    [FOP]              VARCHAR (50)     NULL,
    [TBG_TEMP]         VARCHAR (50)     NULL,
    [SPM_COUNT]        VARCHAR (50)     NULL,
    [STR_LEN]          VARCHAR (50)     NULL,
    [FREQ_HZ]          VARCHAR (50)     NULL,
    [ESP_AMP]          VARCHAR (50)     NULL,
    [SEP_PRESS]        VARCHAR (50)     NULL,
    [FLOWLINE_PRESS]   VARCHAR (50)     NULL,
    [OIL_API_GRAVITY]  VARCHAR (50)     NULL,
    [JOINT_COUNT]      VARCHAR (50)     NULL,
    [COMMENT]          VARCHAR (50)     NULL,
    [CreatedTime]      DATETIME         NULL,
    [CreatedBy]        NVARCHAR (100)   DEFAULT (user_name()) NULL,
    [PubConnID]        INT              NULL,
    [LastModifiedTime] DATETIME         NULL,
    [LastModifiedBy]   NVARCHAR (200)   NULL,
    CONSTRAINT [PK_tbl_IFace_WellTestAutomationToIngres] PRIMARY KEY CLUSTERED ([TransID] ASC, [TransSeq] ASC)
);

