CREATE TABLE [dbo].[tbl_IFace_GasLoaderTrans_tmp] (
    [TransID]               INT              IDENTITY (1, 1) NOT NULL,
    [TransSeq]              INT              NOT NULL,
    [IFaceBatchUID]         UNIQUEIDENTIFIER NOT NULL,
    [TranStatus]            INT              NULL,
    [TranDate]              DATETIME         NULL,
    [TranMsg]               NVARCHAR (MAX)   NULL,
    [PubID]                 INT              NOT NULL,
    [PubConnID]             INT              NULL,
    [LocationID]            VARCHAR (20)     NULL,
    [LocAccountNumber1]     VARCHAR (14)     NULL,
    [LocAccountNumber2]     VARCHAR (14)     NULL,
    [trans_copy]            VARCHAR (10)     NULL,
    [RecordDate]            DATETIME         NULL,
    [AllocActBTUFactor]     VARCHAR (50)     NULL,
    [AllocActPressureBase]  FLOAT (53)       NULL,
    [AllocActWetDryFlag]    VARCHAR (50)     NULL,
    [AllocActGravity]       FLOAT (53)       NULL,
    [AllocActOilVol]        FLOAT (53)       NULL,
    [AllocActNGLVol]        FLOAT (53)       NULL,
    [AllocActGasVolMCF]     FLOAT (53)       NULL,
    [DDAFieldName]          VARCHAR (50)     NULL,
    [DDAFieldNumber]        INT              NULL,
    [BusinessEnitity]       VARCHAR (60)     NULL,
    [LastModifiedTimeStamp] DATETIME         NULL,
    [UserName]              VARCHAR (25)     NULL,
    [CreatedTime]           DATETIME         NULL,
    [CreatedBy]             NVARCHAR (100)   NULL,
    [LastModifiedTime]      DATETIME         NULL,
    [LastModifiedBy]        NVARCHAR (200)   NULL,
    PRIMARY KEY CLUSTERED ([TransID] ASC, [TransSeq] ASC) WITH (FILLFACTOR = 100)
);

