CREATE TABLE [dbo].[tbl_MsgQueue_stg] (
    [MsgQID]                        INT              IDENTITY (1, 1) NOT NULL,
    [TransID]                       INT              NOT NULL,
    [TransSeq]                      INT              NOT NULL,
    [SubIFace]                      NVARCHAR (100)   NOT NULL,
    [PubID]                         INT              NULL,
    [SubID]                         INT              NULL,
    [SubStatus]                     NVARCHAR (50)    NULL,
    [SubDate]                       DATETIME         NULL,
    [SubMsg]                        NVARCHAR (MAX)   NULL,
    [CreatedTime]                   DATETIME         NULL,
    [CreatedBy]                     NVARCHAR (200)   NULL,
    [LastModifiedTime]              DATETIME         NULL,
    [LastModifiedBy]                NVARCHAR (200)   NULL,
    [Description]                   NVARCHAR (MAX)   NULL,
    [IFaceBatchUID]                 UNIQUEIDENTIFIER NULL,
    [SubConnID]                     INT              NULL,
    [PubConnID]                     INT              NULL,
    [ProductType]                   VARCHAR (50)     NULL,
    [DispositionCode]               INT              NULL,
    [DispositionCodeDescription]    VARCHAR (50)     NULL,
    [Sourcetype]                    INT              NULL,
    [CompletionID]                  INT              NULL,
    [GatheringSystemID]             FLOAT (53)       NULL,
    [AreaID]                        VARCHAR (15)     NULL,
    [AreaName]                      VARCHAR (30)     NULL,
    [GatheringSystemName]           VARCHAR (40)     NULL,
    [activity_date]                 DATETIME         NULL,
    [BBL]                           FLOAT (53)       NULL,
    [GAL]                           FLOAT (53)       NULL,
    [MCF]                           FLOAT (53)       NULL,
    [BTU_content]                   FLOAT (53)       NULL,
    [BTU_pressure_base]             FLOAT (53)       NULL,
    [BTU_wet_dry_ind]               INT              NULL,
    [WellPlusCompletionName]        VARCHAR (100)    NULL,
    [processing_party]              VARCHAR (50)     NULL,
    [rc_user_key]                   VARCHAR (20)     NULL,
    [Arg_Det_Sequence]              VARCHAR (15)     NULL,
    [Agreement_ID]                  VARCHAR (15)     NULL,
    [decktype]                      INT              NULL,
    [AllocationDateStamp]           INT              NULL,
    [AccountantPersonID]            INT              NULL,
    [GatheringSystemLockDate]       DATETIME         NULL,
    [GatheringSystemLockName]       VARCHAR (100)    NULL,
    [GatheringSystemAccountantName] VARCHAR (100)    NULL,
    PRIMARY KEY CLUSTERED ([MsgQID] ASC) WITH (FILLFACTOR = 100)
);

