CREATE TABLE [dbo].[tbl_XSPOC_WellTest] (
    [WTID]        INT            IDENTITY (1, 1) NOT NULL,
    [WELUWINTID]  FLOAT (53)     NULL,
    [TESTDATE]    NVARCHAR (8)   NULL,
    [OIL]         FLOAT (53)     NULL,
    [GAS]         FLOAT (53)     NULL,
    [WATER]       FLOAT (53)     NULL,
    [TESTHRS]     FLOAT (53)     NULL,
    [PUMPHRS]     FLOAT (53)     NULL,
    [SPTCODE]     FLOAT (53)     NULL,
    [WTESTCODE]   NVARCHAR (10)  NULL,
    [TSTSTRKLEN]  FLOAT (53)     NULL,
    [TSTSTRKPM]   FLOAT (53)     NULL,
    [TSTPUMPSIZ]  FLOAT (53)     NULL,
    [WTCSNGPRES]  FLOAT (53)     NULL,
    [WTTBNGPRES]  FLOAT (53)     NULL,
    [H2OCUT]      FLOAT (53)     NULL,
    [PMPEFF]      FLOAT (53)     NULL,
    [TSTCHOKSIZ]  FLOAT (53)     NULL,
    [TSTLONGCMT]  NVARCHAR (MAX) NULL,
    [TSTFLLPRES]  FLOAT (53)     NULL,
    [TSTGLGAS]    NVARCHAR (100) NULL,
    [TSTGOR]      FLOAT (53)     NULL,
    [TSTOILGRAV]  FLOAT (53)     NULL,
    [WTTBNGTMPR]  FLOAT (53)     NULL,
    [TSTHPGAS]    FLOAT (53)     NULL,
    [TSTLPGAS]    FLOAT (53)     NULL,
    [TSTCASGAS]   FLOAT (53)     NULL,
    [WTFAP]       FLOAT (53)     NULL,
    [WTPIP]       FLOAT (53)     NULL,
    [WTAMPS]      FLOAT (53)     NULL,
    [WTINJWTRGR]  FLOAT (53)     NULL,
    [PBHP]        FLOAT (53)     NULL,
    [WTMOTRHZ]    FLOAT (53)     NULL,
    [PMPNTAK]     FLOAT (53)     NULL,
    [RECORD]      FLOAT (53)     NULL,
    [WTGASGRTY]   FLOAT (53)     NULL,
    [SEPPRES]     FLOAT (53)     NULL,
    [WTBSW]       FLOAT (53)     NULL,
    [CreatedTime] DATETIME       NULL,
    [CreatedBy]   NVARCHAR (100) DEFAULT (user_name()) NULL,
    CONSTRAINT [PK_tbl_XSPOC_WellTest] PRIMARY KEY CLUSTERED ([WTID] ASC)
);

